name: Build
on:
  push:
    branches: [ 'main' ]

# This job is to build a Windows Installer and will only run on main branch
jobs:
  build-windows:
    name: Build and Package for Windows
    runs-on: windows-2022
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"

    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.9.1'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: 'true'

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 4.1.0

      - name: Restore Cache LibDataChannel
        id: cache-libdatachannel-restore
        uses: actions/cache/restore@v4
        with:
          path: 'C:/Program Files (x86)/libdatachannel'
          key: ${{ runner.os }}-libdatachannel

      - name: Build LibDataChannel
        working-directory: ${{ runner.workspace }}
        if: steps.cache-libdatachannel-restore.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/paullouisageneau/libdatachannel.git
          cd libdatachannel
          git checkout v0.24.1
          git submodule update --init --recursive --depth 1
          cmake -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DNO_EXAMPLES=ON
          cmake --build build --config Release
          cmake --install build

      - uses: dtolnay/rust-toolchain@stable
        name: Install Rust

      - name: Build Vodozemac Bindings
        working-directory: ${{ github.workspace }}/vodozemac
        run: cargo build

      - name: Build Sharity
        working-directory: ${{ github.workspace }}/client
        run: |
          cmake -B build  -G "Visual Studio 17 2022" -DQt6_DIR="C:\Qt\6.9.1\msvc2022_64" -DCONFIGURE_NSIS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - uses: winpax/scoop-setup@v1.0.0
        name: Install NSIS
        with:
          buckets: extras
          apps: nsis

      - name: Package NSIS
        working-directory: ${{ github.workspace }}/client/build
        run: cpack .

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/client/build/Sharity-*-win64.exe

      - name: Save Cache LibDataChannel
        id: cache-libdatachannel-save
        uses: actions/cache/save@v4
        if: always() && steps.cache-libdatachannel-restore.outputs.cache-hit != 'true'
        with:
          path: 'C:/Program Files (x86)/libdatachannel'
          key: ${{ runner.os }}-libdatachannel

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"

    steps:
      - uses: actions/checkout@v5

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y libsrtp2-dev ninja-build

      - name: Install CMake
        working-directory: ${{ runner.workspace }}
        run: |
          mkdir cmake
          cd cmake
          curl -LO https://github.com/Kitware/CMake/releases/download/v4.1.0/cmake-4.1.0-linux-x86_64.sh
          chmod +x cmake-4.1.0-linux-x86_64.sh
          ./cmake-4.1.0-linux-x86_64.sh --skip-license
          rm cmake-4.1.0-linux-x86_64.sh
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - uses: dtolnay/rust-toolchain@stable
        name: Install Rust

      - uses: jurplel/install-qt-action@v4
        name: Install Qt
        with:
          host: linux
          dir: $RUNNER_WORKSPACE

      - name: Cache LibDataChannel
        id: cache-libdatachannel
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/libdatachannel
          key: ${{ runner.os }}-libdatachannel

      - name: Build LibDataChannel
        working-directory: ${{ runner.workspace }}
        if: steps.cache-libdatachannel.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/paullouisageneau/libdatachannel.git
          cd libdatachannel
          git checkout
          git checkout v0.24.1
          git submodule update --init --recursive --depth 1
          cmake -B build -GNinja -DNO_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_SRTP=ON
          cmake --build build

      - name: Install LibDataChannel
        working-directory: ${{ runner.workspace }}/libdatachannel
        run: sudo cmake --install build

      - uses: dtolnay/rust-toolchain@stable
        name: Install Rust

      - name: Build Vodozemac
        working-directory: ${{ github.workspace }}/vodozemac
        run: cargo build

      - name: Build Sharity
        working-directory: ${{ github.workspace }}/client
        run: |
          cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build
